export const projects = [
	{
		title: 'Konga SuperApp',
		description: 'Konga Super App',
		image: '/images/super-app.png',
		tags: ['Typescript', 'React', 'Styled Components', 'Material UI', 'Redux'],
		visit: '#',
		source: 'https://new.konga.com/',
		id: 0,
	},
	{
		title: 'DJ Events',
		description: 'A platform to show DJ Events coming up',
		image: '/images/dj-events.png',
		tags: ['Next Js', 'React', 'Strapi', 'PostgreSql'],
		visit: 'https://github.com/nkemjikaobi/dj-events-frontend',
		source: 'https://djeventsfrontend-derick.vercel.app/',
		id: 13,
	},
	{
		title: 'Space X',
		description:
			'An application consuming endpoints from space X using GraphQL and React Apollo Client',
		image: '/images/space-x.png',
		tags: ['Next Js', 'React', 'Strapi', 'PostgreSql'],
		visit: 'https://github.com/nkemjikaobi/spaceX',
		source: 'https://derick-spacex.herokuapp.com/',
		id: 14,
	},
	{
		title: 'My Resume',
		description: 'My Portfolio',
		image: '/images/resume.png',
		tags: ['Next Js', 'React', 'Styled Components'],
		visit: 'https://github.com/nkemjikaobi/my-resume',
		source: 'https://obi-nkemjika.netlify.app/',
		id: 1,
	},
	{
		title: 'Zuri Chat',
		description: 'Zuri Chat',
		image: '/images/zuri-chat.png',
		tags: ['Node Js', 'React', 'Styled Components', 'Material UI', 'Redux'],
		visit: 'https://github.com/zurichat',
		source: 'https://zuri.chat/',
		id: 2,
	},
	{
		title: 'Farm Hailing',
		description: 'Farm Hailing',
		image: '/images/hailing.png',
		tags: ['React', 'Context UI', 'Redux'],
		visit: '#',
		source: 'https://staging.d1ro86o0zojtyp.amplifyapp.com/',
		id: 3,
	},
	{
		title: 'Contact Keeper',
		description:
			'This is a web application to assist users in storing contacts.',
		image: '/images/contact-keeper.png',
		tags: ['MongoDB', 'Context API', 'Express', 'React', 'Node'],
		visit: 'https://github.com/nkemjikaobi/contact-keeper',
		source: 'https://deric-contact-keeper.herokuapp.com/',
		id: 5,
	},
	{
		title: 'Dericasts',
		description:
			'A web application to check the current weather of any city worldwide',
		image: '/images/dericasts.png',
		tags: ['React', 'JavaScript', 'Open Weather API', 'Docker'],
		visit: 'https://github.com/nkemjikaobi/dericasts',
		source: 'https://dericasts.netlify.app/',
		id: 6,
	},
	{
		title: 'Deribooks',
		description:
			'This is a web application that enables users create public and private stories as well as read the stories of other users.',
		image: '/images/dericbooks.png',
		tags: ['React', 'MongoDB', 'Express', 'Node', 'Passport', 'Moment'],
		visit: 'https://github.com/nkemjikaobi/deribooks',
		source: 'http://deribooks.herokuapp.com',
		id: 7,
	},
	{
		title: 'Student Profile',
		description:
			'A web application that displays student profiles, calculates grades and also filters by names and tags',
		image: '/images/student-profile.png',
		tags: ['React', 'Axios', 'UUID', 'React-Toast-Notifications'],
		visit: 'https://github.com/nkemjikaobi/hatchways',
		source: 'https://hatchways-evaluation.herokuapp.com/',
		id: 8,
	},
	{
		title: 'GitHub Finder',
		description:
			'This is a web application that searches through public repositories of users on GitHub. It also displays GitHub profile of the user',
		image: '/images/github-finder.png',
		tags: ['React', 'Axios', 'GitHub'],
		visit: 'https://github.com/nkemjikaobi/dericks-github-finder',
		source: 'https://dericks-github-finder.netlify.app/',
		id: 9,
	},
	{
		title: 'IT Logger',
		description:
			'This is a web application for IT technicians to add logs in order of priority i.e High or Low attention. Logs can be added and must be associated with a technicians',
		image: '/images/it-logger.png',
		tags: ['React', 'Redux', 'Axios', 'Node Js', 'Mongo DB'],
		visit: 'https://github.com/nkemjikaobi/IT-Logger-node-express',
		source: 'https://derick-it-logger.herokuapp.com/',
		id: 10,
	},
	{
		title: 'Knack',
		description:
			'An Employee Directory. This is a web application for an individual to view all employees in an organization, schedule meetings with available employees and also create surveys',
		image: '/images/knack.png',
		tags: ['React', 'Context API', 'Materialize', 'Node Js'],
		visit: 'https://github.com/nkemjikaobi/knack',
		source: 'https://knack-co.herokuapp.com/',
		id: 11,
	},
	{
		title: 'Deroku',
		description: 'A website for a fictional hosting company',
		image: '/images/deroku.png',
		tags: ['Html', 'Css'],
		visit: 'https://github.com/nkemjikaobi/knack',
		source: 'https://deroku.netlify.app/',
		id: 12,
	},
];

export const TimeLineData = [
	{ year: 2017, text: 'Data Entry Clerk at Bollore Transport and Logistics' },
	{ year: 2019, text: 'Computer Science Instructor' },
	{ year: 2020, text: 'BackEnd Developer at Hotels NG(HNGi7)' },
	{ year: 2020, text: 'BackEnd Developer at WeJapa' },
	{
		year: 2020,
		text: 'Mobile Web Specialist at Google Africa Development Scholarships',
	},
	{ year: 2021, text: 'Software Engineer at Konga' },
];
